### ISSUE TITLE
If script is stopped, it may tweet same images.

### ISSUE THREAD

**Issue by hawkfalcon** [hawkfalcon/RedditTwitterBot#3]
Would be fixed by storing a file w/ contents of 'posted'

**Comment by NickParks** [comment]
Easy to fix, create a .json file and use the already loaded fs (file system) module to read and write to it every time it checks for a new set of 'hot' posts.

Could be easier done by simply overwriting the file every time with the current 'posted' list/array you have. And when the script is first created (I believe there is some way of doing this in node/js). Load the file/json from it.

Ye, #Swag
